version: '3.8'

services:

 db:
  container_name: fastapi_tdd_dev_db
  image: postgres
  restart: always
  volumes: 
   - postgres_data:/var/lib/postgresql/data/
  expose:
   - 5432:5432
  environment:
   - POSTGRES_USER=fastapi_tdd
   - POSTGRES_PASSWORD=fastapi_tdd
   - POSTGRES_DB=fastapi_tdd_dev

 pgadmin:
  container_name: pgadmin
  image: dpage/pgadmin4
  environment:
   - PGADMIN_DEFAULT_EMAIL=admin@mail.com
   - PGADMIN_DEFAULT_PASSWORD=Password@1
  ports:
   - 5050:80
  depends_on:
   - db

 web:
  build: ./src
  #command: python ./app/main.py
  volumes:
      - ./src/:/usr/src/app/
  ports:
      - 8002:8000
  depends_on:
      - db


volumes:
 postgres_data:



